### ISSUE TITLE
videojs-playlist.js build calls incorrect function

### ISSUE THREAD

**Issue by d3athrow** [brightcove/videojs-playlist#264]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/).

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Build new dist
2. Load test page
3. get error

### Expected
Please describe what you expected to see.
No error
### Actual
Please describe what actually happened.
Error in console
### Error output
If there are any errors at all, please include them here.
```
Uncaught TypeError: this.playlist_.get is not a function
    at PlaylistPlugin.loadPlaylistItem (videojs-playlist.js:651:36)
    at PlaylistPlugin.loadFirstItem (videojs-playlist.js:669:19)```
## Additional Information
Please include any additional information necessary here. Including the following:

### versions
#### videojs
what version of videojs does this occur with?
whatever is defined in package.json
#### browsers
what browser are affected?

#### OSes
what platforms (operating systems and devices) are affected?

### plugins
are any videojs plugins being used on the page? If so, please list them below.
NO


.get() does not exist, it should be .getItems()

**Comment by mister-ben** [comment]
Thanks for the report. If you weren't aware, note the main branch is the v6 release candidate. [v5.1.2](https://github.com/videojs/videojs-playlist/tree/v5.1.2) reflects `latest` on npm.
